# Configuration for Dependabot
# See https://help.github.com/articles/configuring-automated-security-fixes

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
